name: Clean, Build, Commit, Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Clean build folder
    - run: |
        rm dist/*
        git rm dist/*

    - name: Build dist
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm ci
        npm run build

    - name: Commit Changes
      run: |
          git config --local user.name "github-bot"
          git add dist/*
          git commit -m "Update build files"
    
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true