name: NodeJS with Webpack

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: rm dist/*
    - run: npm run build

    - name: Update dist
      uses: test-room-7/action-update-file@v1.6.0
      with:
        # Commit message
        commit-msg: update bundle
        # Path to file(s) or glob pattern
        file-path: dist/*
        # GitHub token
        github-token: ${{ secrets.GITHUB_TOKEN }}
